version: '3'
services:
  web:
    image: nginx
    volumes:
     - ./dist:/var/www
     - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
    depends_on:
      - nodejs
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinko-creator-nodejs
    user: node
    command: npm run prerender
    volumes:
      - .:/home/node/app
