// Custom styles
export const styles = {
  cover__title: {
    font: 'Museo',
    fontSize: 38,
    color: '#FFFFFF',
    bold: true,
  },
  cover__subtitle: {
    fontSize: 18,
    characterSpacing: 0.26,
    font: 'PTSans',
    color: '#FFFFFF',
    lineHeight: 1.2,
  },
  header: {
    font: 'Museo',
    fontSize: 10,
    color: '#141C3A',
    opacity: 0.3,
    characterSpacing: 0.3,
    alignment: 'right',
    margin: [0, 30, 40, 0],
  },
  footer: {
    font: 'Museo',
    fontSize: 10,
    color: '#141C3A',
    opacity: 0.3,
    characterSpacing: 0.3,
  },
  footer__cover: {
    fontSize: 10,
    color: '#FFFFFF',
    font: 'Museo',
    characterSpacing: 1.7,
    bold: true,
    alignment: 'left',
    margin: [40, 0, 0, 0],
  },
  footer_link: {
    decoration: 'underline',
    decorationColor: '#141C3A',
  },
  overview__title: {
    font: 'Museo',
    fontSize: 24,
    characterSpacing: 0.19,
    margin: [0, 0, 0, 12],
    bold: true,
  },
  overview__description: {
    font: 'PTSans',
    fontSize: 10,
    characterSpacing: 0.2,
    margin: [0, 0, 0, 25],
    lineHeight: 1.15,
  },
  overview__subTitle: {
    font: 'Museo',
    fontSize: 8,
    lineHeight: 0.5,
    characterSpacing: 0,
    margin: [0, 0, 0, 15],
  },
  overview__data: {
    fillColor: '#FAFBFB',
    margin: [15, 10, 15, 10],
    font: 'PTSans',
    characterSpacing: 0.3,
    fontSize: 8,
    lineHeight: 1.1,
  },
  overview__tableContent: {
    margin: [0, 10, 0, 10],
    lineHeight: 1.25,
  },
  tableHeader: {
    alignment: 'center',
    color: '#FFFFFF',
    fontSize: 10,
    font: 'Museo',
    bold: true,
    characterSpacing: 0.36,
  },
  tableHeaderSmall: {
    fontSize: 8,
    font: 'PTSans',
    bold: false,
    margin: [0, 15],
    characterSpacing: 0.5,
  },
  icon: {
    font: 'Icomoon',
    fontSize: 12,
    color: '#141C3A',
    margin: [0, 0, 5, 0],
  },
  orderedList: {
    bold: true,
    margin: [0, 0, 0, 0],
  },
  subjectHeader: {
    alignment: 'center',
    color: '#FFFFFF',
    fontSize: 10,
    font: 'Museo',
    bold: true,
    characterSpacing: 0.36,
  },
  subjectSubHeader: {
    color: '#141C3A',
    fontSize: 8,
    font: 'Museo',
    bold: false,
    characterSpacing: 0.36,
  },
  subjectSubHeaderCenter: {
    color: '#141C3A',
    fontSize: 8,
    font: 'Museo',
    bold: false,
    characterSpacing: 0.36,
    alignment: 'center',
  },
  mark: {
    fillColor: '#EFE5FC',
    color: '#6400E4',
    fontSize: 12,
    alignment: 'center',
  },
  shortCode: {
    bold: true,
    color: '#858999',
    fontSize: 10,
  },
  shortCodeDesc: {
    color: '#9B9EAB',
    fontSize: 10,
  },
  contentText: {
    fontSize: 8,
    lineHeight: 1.2,
  },
  resumenCell: {
    color: '#fff',
    alignment: 'center',
    characterSpacing: 0.5,
    lineHeight: 1,
    fontSize: 8,
    font: 'Brandon',
  },
  resumenSeparator: {
    color: '#fff',
    fontSize: 7,
    alignment: 'center',
    lineHeight: 1,
  },
  activityMainHead: {
    fontSize: 15,
    bold: true,
    font: 'Museo',
    margin: [0, 0, 0, 5],
    characterSpacing: 0.36,
  },
  activity: {
    fontSize: 8,
    font: 'Brandon',
    characterSpacing: 1,
    bold: true,
    color: '#6400E4',
  },
  activitySeparator: {
    fontSize: 9,
    alignment: 'center',
    color: '#141c3a',
  },
  activityListTitle: {
    font: 'PTSans',
    fontSize: 9,
    color: '#141c3a',
    bold: true,
    characterSpacing: 0.2,
  },
  activityListIcon: {
    fontSize: 9,
    color: '#A8AAB3',
  },
  activityListCellText: {
    fontSize: 8,
    font: 'Brandon',
    characterSpacing: 0.5,
    bold: false,
    color: '#141C3A',
  },
  actDetailPhase: {
    fontSize: 8,
    font: 'Brandon',
    characterSpacing: 1,
    bold: true,
    color: '#6400E4',
  },
  actDetailSeparator: {
    fontSize: 9,
    alignment: 'center',
    color: '#141c3a',
  },
  actDetailIndicator: {
    font: 'Brandon',
    bold: false,
    characterSpacing: 0.5,
    fontSize: 8,
  },
  activityDetailHead: {
    fontSize: 15,
    bold: true,
    font: 'Museo',
    characterSpacing: 0.36,
  },
  activityDetailDesc: {
    fontSize: 8,
    font: 'PTSans',
  },
  activityDetailSubhead: {
    font: 'Museo',
    fontSize: 8,
    margin: [0, 0, 0, 8],
  },
  listGap: {
    margin: [0, 0, 0, 5],
  },
  activityExerciseName: {
    font: 'PTSans',
    bold: true,
    fontSize: 8,
  },
  activityObjectiveNo: {
    font: 'PTSans',
    bold: true,
  },
  activityExerciseStatus: {
    font: 'PTSans',
    bold: false,
    fontSize: 8,
  },
}

// Default styles for PDF
export const defaultStyle = {
  font: 'PTSans',
  alignment: 'left',
  color: '#141C3A',
  fontSize: 10,
}
